---
title: "Collaborative and Reproducible Research: Skills for Effective Communication, Collaboration, and Dissemination"
author: "Jessica L. Burnett"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: 
  pdf_document:
  # md_document:
  #   variant: markdown_github
bibliography: rr_course.bib
header-includes:
- \usepackage{pdflscape}
- \newcommand{\blandscape}{\begin{landscape}}
- \newcommand{\elandscape}{\end{landscape}}
--- 

# Course Webpage and Online Resources  
[Click here for the course webpage](https://github.com/TrashBirdEcology/courses/tree/master/rr_course)

# Course Description  

Collaborative research (team science) can lead to ideas, products, and information of high quality and impact, yet is a skill rarely formally taught to students. Reproducibility is a key component for effective communication within and outside collaborative research teams. Understanding and applying reproducible research practices benefits the efficiency and effectiveness of the team and its members, and is increasingly relevant as long-distance collaborations are becoming commonplace. Students in this course will learn and apply the basic tenents of reproducible research in a group-setting. This course will use lectures, discussion, and computer laboratory components culminating in a collaborative, data-driven research project. Short lectures and discussions will introduce the topic of and background for each computer-based laboratory meeting, where students will apply the knowledge and skills learned. Basic proficiency in a programming language and a desire to design and conduct a peer-reviewed research project is required. Although we will focus on conducting reproducible research in R and on GitHub, the basic skills learned are transferrable across research tools and domains. 

*Prerequisites*. No formal prerequisites or prior programming skills are required, however, students must be willing to learn and practice using open-sourced platforms and software (e.g., Github, Google Drive, Overleaf) is required. 
<!-- Skills in using specific tools will be introduced, but not assessed. -->

<!-- This course provides students the basic skills and knowledge required to produce and become ambassadors for reproducible and collaborative research. Knowledge and skills will be facilitated using lectures, discussions, computer laboratory exercises. Students will demonstrate knowledge through homework assignments, reflections, and design and conduct a small project with two or more peers. The hands-on and group activities are designed such that the students are exposed to many aspects of scientific research, collaboration, and reproducibility. In other words, the schedule is designed to allow for ample learning via trial-and-error. -->

## Intended Audience
The course is intended for graduate students and, with instructor permission, upper-level undergraduate students. No prior programming is necessary. 


# Statement on Diversity and Inclusivity  
Heterogeneity is valued in natural and social systems. I strive to create a safe and inclusive environment within which we can each learn from and teach one another. It is the diverse experiences of others from which we most benefit. Disciminatory remarks or actions will not be tolerated.


# Course Objectives and Core Questions

Two questions drive the content of this course:  
1. **What are the cons of reproducible research?**  
1. **What are the cons of open science?**  

By the end of this course students will have the skills to lead and participate in collaborative research projects, and produce and share research in a reproducible manner. Specifically, students will be able to:

- Describe the components, benefits, and challenges of collaborative research
- Describe the components, benefits, and challenges of reproducibile research
- Conduct a scientific research peer review 
- Demonstrate proficiency in creating a reproducible research project 
- Gain first-hand experience in team-based research 
- Plan and conduct research with multiple collaborators 


### 1. Reproducibile Research  
- Objectives
  - Explain the components and utility of reproducible research
  - Identify and practice using the tools and resources for creating reproducible research
  - Summarise the reproducibility of a published research project

- Core Questions
  - What are the cons of reproducible research?
  - What are the cons of Open Science?

### 2. Collaboration: Benefits, Skills, and Tools    
- Objectives
  - Identify and practice using the tools and resources for efficient collaboration
  - Describe the benefits and challenges associated with collaboration
  - Identify opportunities for collaboration
  - Understand the relevance of communication in collaboration
  
- Core Questions
  - [When] does collaboration work and fail?

### 3. Team Science   
- Objectives
  - Identify and practice using the tools and resources for efficient collaboration
  - Describe the benefits and challenges associated with collaboration
  - Identify opportunities for collaboration
  - Understand the relevance of communication in collaboration
  
- Core Questions
  - Are you a team player?
  
  
### 4. Peer Review and Dissemination  
- Objectives
  - Understand the components and purpose of peer reviews in science
  - Improve your ability to provide peer reviews 
  - Practice receiving and responding to peer reviews
  
- Core Questions
  - What, if any, role should peer review play in your research?


\newpage
\blandscape
# Course Schedule  
## Lectures & Discussions 

Module | Week | Topic | Discussion Facilitator 
:---|:---:|-------------------------|-----
1 | 01 | Review tenents of reproducible research | Burnett
1 | 02 | Documentation & organization: data organization & importance of w.r.t. reproducibility | Burnett
1 | 03 | Documentation & organization: project directories | Burnett
1 | 04 | Peer reviews of WK 3 HW | 
2 | 05 | Collaboration: importance and components | Group A
2 | 06 | Collaboration: team roles, leadership, and team code of conduct | Group B
2 | 07 | Identifying projects and identify team members and their roles. Discuss code of conduct | Burnett
3 | 08 | Collaboration: benefits and challenges | Group C
3 | 09 | Doing collaborative research: collaborative writing and literature review. Review tools for citation management and sharing. | Burnett
3 | 10 | Doing collaborative research: computational analyses and sharing.  | Group D
3 | 11 | Building your network | Group E
4 | 12 | Peer review process: purpose, components and how-to | Group F
4 | 13 | Getting the job done: reaching out to new collaborators | Burnett
4 | 14 | Dissemination: where and how to publish and share your work | Burnett
4 | 15 | Final project due! Discuss reflections (HW). |
\newpage

## Labs and Homework  

Unit | Week | Lab Activity | Homework (due before next lab period) 
:--|:--:|--------------------|----------------------
1 | 01 | Review examples of various levels of reproducible project. Identify good and bad components. | 
1 | 02 | Review best practices for data organization and documenting in real-time.  | Design a datasheet structure from the provided project summary.
1 | 03 | Practice building project footprints in OS of choice. | Improve the structure and documentation for an existing project of your choice and reflect upon the improvements.
1 | 04 | Review and practice using tools for data sharing and documentation. | Reflect ($\leq1$ page) on a past professional collaboration. If none, reflect on this week's discussion. Consider potential data analyses/project ideas. 
2 | 05 | Review tools for collaboration: writing, analysis, and general communication. Identify the pros and cons of each. |  Summarise (bullets) research interests and potential skills you could bring to a research project (also complete the associated Google Form).
2 | 06 | Brief overview of potential project ideas. Identify potential collaborations using research interests and skills.  | Upload your research project idea(s) to the class project directory by end of business day. Identify 2-3 projects you may be interested in joining. 
2 | 07 | Identify the digital tools to be used to achieve your project. Initialize the project directory. Brainstorm project questions and timeline. / project ideas and identifying tools | Work with your group online and/or in person to create at least one brief project 'pre-proposal'.  
3 | 08 | Identify the statistical or numerical approaches required to answer your questions. Identify outside expertise or manpower required to complete your project. | As a group, write a 1-2 page proposal including the analytical approach (will provide an example). Specify or create the license for data source. Find a model data management plan. Identify potential location(s) for archiving your data and analyses. 
3 | 09 | Work on projects.  | 
3 | 10 | Work on projects.  | 
4 | 11 | Work on proejcts. Feedback from guest experts. | 
4 | 12 | Group project updates and reflections. Work on projects. | 
3 | 13 | Work on projects. | 
4 | 14 | Begin among-group peer reviews and submit within-group peer evaluations. | Peer reviews and evaluations due by next week's lab. Write a <1 page reflection on the project, team dynamics.  
4 | 15 | Present and discuss research project and reflections on the collaborative experience. Demonstrate the reproducibility of your project. | 

  
## Prior to first meeting 
Before the first week of class,   
- [inform instructor of your prior background]()<- this will be a link to a google form to ID baselines for the course
- consider potential data and/or research project ideas for a collaborative research project 
<!-- - install Program R and R Studio (required)* [Introduction to RStudio](https://youtu.be/FNrCxTSzq6s)   -->
<!-- - [create GitHub account](https://datadryad.org/password-login) -->
<!-- - [create Dryad account](https://datadryad.org/password-login) -->
<!-- - [create ORCID account](https://datadryad.org/password-login) -->

\elandscape
\newpage
# Graded Work
**10% Discussion**  
Students will work in small teams to lead one weekly discussion of a paper, website, or other resource related to the week's topic. Resource(s) should be approved by the instructor by the beginning of the class period of the week prior to their assigned discussion. 

**5% Collaboration Reflections** 
Students will briefly ($\leq 1$ page) reflect upon various stages of the collaborative resaerch project.

**10% Collaborative Project Pre-proposals**  
Groups will collectively propose 2-4 potential projects. Groups can submit a single proposal with prior approval of the instructor. Pre-proposals will be evaluated on originality and quality of their submission.


**20% Collaborative Project Proposals**  
Groups will propose 1-2 potential projects. Students will be evaluated on originality and quality of their submitted assignments throughout the course. Assignments include the group proposals and peer review. 

**40% Collaborative Project Writeup**  
The end product of this course will be a manuscript draft resulting from the collaboration of between 2 and 5 students. collaborative project with the goal of report or manuscript submission. Groups will be identified at the end of Week 2, and will collectively write short project proposals for submission in Week XX. The group project will be graded based on the transparency, reproducibility, and overall quality of the computational and written components. *If the group cannot identify/agree upon a project by the deadline, a dataset will be provided by the instructor. Groups are encouraged to seek feedback often and early. 

**10% Group Peer Reviews**  
Students will conduct peer reviews of 1-2 other team projects. The peer reviewers will be evaluated on the quality of their submissions. 

**5% Peer Evaluations**  
Students will provide peer reviews of their team members' involvement in the project. The instructor will provide a final score based on all group memebers' peer evaluations and prior knowledge. 

